ALTER TABLE items
  ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE bosses
  ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE npcs
  ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);
